import IconsName from '../../images/IconsName';

export const Theme = [
  {
    key: 'W1',
    EN: 'Warning signs',
    PL: 'Znaki ostrzegawcze',
    DE: 'Warnsignale',
    icon: IconsName.warning,
  },
  {
    key: 'W2',
    EN: 'Prohibition and mandatory signs',
    PL: 'Znaki zakazu, nakazu',
    DE: 'Verbots- und Gebotszeichen',
    icon: IconsName.prohibited,
  },
  {
    key: 'W3',
    EN: 'Additional information, direction and location signs',
    PL: 'Znaki informacyjne, kierunku i miejscowości, uzupełniające',
    DE: 'Zusätzliche Informationen, Wegweiser und Ortsschilder',
    icon: IconsName.curve,
  },
  {
    key: 'W4',
    EN: 'Horizontal road signs',
    PL: 'Znaki drogowe poziome',
    DE: 'Horizontale Verkehrsschilder',
    icon: IconsName.road_sign,
  },
  {
    key: 'W5',
    EN: 'Light signals, signals given by the traffic controller',
    PL: 'Sygnały świetlne, sygnały dawane przez kierującego ruchem',
    DE: 'Lichtsignale, Signale des Verkehrsleiters',
    icon: IconsName.traffic_lights,
  },
  {
    key: 'W6',
    EN: 'Joining traffic, peer intersections',
    PL: 'Włączanie się do ruchu, skrzyżowania równorzędne',
    DE: 'Einmündung in den Verkehr, gleiche Kreuzungen',
    icon: IconsName.merging,
  },
  {
    key: 'W7',
    EN: 'Crossings with right-of-way signs',
    PL: 'Skrzyżowania ze znakami określającymi pierwszeństwo przejazdu',
    DE: 'Kreuzung mit Vorfahrtsschildern',
    icon: IconsName.crossroad,
  },
  {
    key: 'W8',
    EN: 'Intersections with traffic lights',
    PL: 'Skrzyżowania z sygnalizacją świetlną',
    DE: 'Kreuzung mit Ampeln',
    icon: IconsName.traffic_light,
  },
  {
    key: 'W9',
    EN: 'Crossings or crossings for pedestrians with traffic control, public transport stops',
    PL: 'Skrzyżowania lub przejścia dla pieszych z kierujących ruchem, miejsca przystanków komunikacji publicznej',
    DE: 'Kreuzungen oder Fußgängerüberwege mit Verkehrskontrolleuren, Haltestellen öffentlicher Verkehrsmittel',
    icon: IconsName.high_visibility_vest,
  },
  {
    key: 'W10',
    EN: 'The position of the vehicle on the road, entering and exiting an intersection, stopping and parking',
    PL: 'Pozycja pojazdu na drodze, wjazd i zjazd ze skrzyżowania, zatrzymanie i postój',
    DE: 'Fahrzeugposition auf der Straße, Ein- und Ausfahrt aus der Kreuzung, Anhalten und Parken',
    icon: IconsName.parking,
  },
  {
    key: 'W11',
    EN: 'Lane change, change of driving direction',
    PL: 'Zmiana pasa ruchu, zmiana kierunku jazdy',
    DE: 'Spurwechsel, Richtungswechsel',
    icon: IconsName.directions,
  },
  {
    key: 'W12',
    EN: 'Overtaking',
    PL: 'Wyprzedzanie',
    DE: 'Überholen',
    icon: IconsName.no_overtaking,
  },
  {
    key: 'W13',
    EN: 'Avoid, Pass, Back',
    PL: 'Omijanie, wymijanie, cofanie',
    DE: 'Ausweichen, Überholen, Rückwärtsfahren',
    icon: IconsName.two_way_street,
  },
  {
    key: 'W14',
    EN: 'Use of exterior lights and vehicle signals',
    PL: 'Używanie świateł zewnętrznych i sygnałów pojazdu',
    DE: 'Verwendung von Außenlichtern und Fahrzeugsignalen',
    icon: IconsName.autonomous_car,
  },
  {
    key: 'W15',
    EN: 'The importance of taking special care towards other road users, getting out of the vehicle, securing the vehicle',
    PL: 'Znaczenie zachowania szczególnej ostrożności w stosunku do innych użytkowników drogi',
    DE: 'Es ist wichtig, gegenüber anderen Verkehrsteilnehmern besondere Vorsicht walten zu lassen',
    icon: IconsName.accident,
  },
  {
    key: 'W16',
    EN: 'Behavior towards a pedestrian, towards a person with reduced mobility',
    PL: 'Zachowanie wobec pieszego, wobec osoby o ograniczonej możliwości poruszania się',
    DE: 'Verhalten gegenüber einem Fußgänger, gegenüber einer Person mit eingeschränkter Mobilität',
    icon: IconsName.disability,
  },
  {
    key: 'W17',
    EN: 'Behavior towards cyclists and children',
    PL: 'Zachowanie wobec rowerzysty i dzieci',
    DE: 'Verhalten gegenüber Radfahrern und Kindern',
    icon: IconsName.pedestrian,
  },
  {
    key: 'W18',
    EN: 'Behavior at railway and tram crossings',
    PL: 'Zachowanie na przejazdach kolejowych i tramwajowych',
    DE: 'Verhalten an Bahn- und Straßenbahnübergängen',
    icon: IconsName.level_crossing,
  },
  {
    key: 'W19',
    EN: "General rules defining the driver's behavior in the event of a breakdown or accident, providing first aid",
    PL: 'Ogólne zasady określające zachowanie kierowcy w momencie awarii lub wypadku',
    DE: 'Allgemeine Regeln, die das Verhalten des Fahrers im Falle einer Panne oder eines Unfalls festlegen',
    icon: IconsName.risk,
  },
  {
    key: 'W20',
    EN: 'Perception, judgment and decision making, especially with regard to reaction time and changes in driving behavior due to the influence of alcohol, drugs and medicinal products, state of consciousness and fatigue',
    PL: 'Spostrzeganie, ocena sytuacji i podejmowanie decyzji, szczególnie w zakresie czasu reakcji oraz zmian w zachowaniu za kierownicą, spowodowanych wpływem alkoholu, leków i produktów leczniczych, stanem',
    DE: 'Wahrnehmung, Einschätzung der Situation und Entscheidungsfindung, insbesondere im Hinblick auf Reaktionszeit und Veränderungen des Fahrverhaltens durch Alkohol-, Drogen- und Arzneimitteleinfluss',
    icon: IconsName.learner,
  },
];
