import IconsName from './IconsName';

export default function getIcons(name) {
  switch (name) {
    case IconsName.road:
      return require('./photos/road.png');
    case IconsName.crossroad:
      return require('./photos/crossroad.png');
    case IconsName.curve:
      return require('./photos/curve.png');
    case IconsName.merging:
      return require('./photos/merging.png');
    case IconsName.prohibited:
      return require('./photos/prohibited.png');
    case IconsName.road_sign:
      return require('./photos/road-sign.png');
    case IconsName.traffic_lights:
      return require('./photos/traffic-lights.png');
    case IconsName.warning:
      return require('./photos/warning.png');
    case IconsName.accident:
      return require('./photos/accident.png');
    case IconsName.autonomous_car:
      return require('./photos/autonomous-car.png');
    case IconsName.directions:
      return require('./photos/directions.png');
    case IconsName.disability:
      return require('./photos/disability.png');
    case IconsName.high_visibility_vest:
      return require('./photos/high-visibility-vest.png');
    case IconsName.learner:
      return require('./photos/learner.png');
    case IconsName.ddriver:
      return require('./photos/level-crossing.png');
    case IconsName.diffRoadCond:
      return require('./photos/no-overtaking.png');
    case IconsName.parking:
      return require('./photos/parking.png');
    case IconsName.pedestrian:
      return require('./photos/pedestrian.png');
    case IconsName.risk:
      return require('./photos/risk.png');
    case IconsName.two_way_street:
      return require('./photos/two-way-street.png');
    case IconsName.traffic_light:
      return require('./photos/traffic-light.png');
    case IconsName.a_category:
      return require('./photos/a_category.png');
    case IconsName.a1_category:
      return require('./photos/a1_category.png');
    case IconsName.a2_category:
      return require('./photos/a2_category.png');
    case IconsName.am_category:
      return require('./photos/am_category.png');
    case IconsName.b_category:
      return require('./photos/b_category.png');
    case IconsName.brakes:
      return require('./photos/brakes.png');
    case IconsName.c_category:
      return require('./photos/c_category.png');
    case IconsName.c1_category:
      return require('./photos/c1_category.png');
    case IconsName.cancel:
      return require('./photos/cancel.png');
    case IconsName.category:
      return require('./photos/category.png');
    case IconsName.checked:
      return require('./photos/checked.png');
    case IconsName.d_category:
      return require('./photos/d_category.png');
    case IconsName.d1_category:
      return require('./photos/d1_category.png');
    case IconsName.day_and_night:
      return require('./photos/day_and_night.png');
    case IconsName.ddriver:
      return require('./photos/ddriver.png');
    case IconsName.diffRoadCond:
      return require('./photos/diffRoadCond.png');
    case IconsName.documents:
      return require('./photos/documents.png');
    case IconsName.drivingTechnique:
      return require('./photos/drivingTechnique.png');
    case IconsName.eyes:
      return require('./photos/eyes.png');
    case IconsName.first_aid:
      return require('./photos/first_aid.png');
    case IconsName.forbidden:
      return require('./photos/forbidden.png');
    case IconsName.germany:
      return require('./photos/DE.png');
    case IconsName.half_moon:
      return require('./photos/half_moon.png');
    case IconsName.heart_1:
      return require('./photos/heart_1.png');
    case IconsName.heart_fill:
      return require('./photos/heart_fill.png');
    case IconsName.locked:
      return require('./photos/locked.png');
    case IconsName.mechanicalAspects:
      return require('./photos/mechanicalAspects.png');
    case IconsName.motoHelmet:
      return require('./photos/motoHelmet.png');
    case IconsName.poland:
      return require('./photos/PL.png');
    case IconsName.pt_category:
      return require('./photos/pt_category.png');
    case IconsName.safetyBelt:
      return require('./photos/safetyBelt.png');
    case IconsName.safetyFactors:
      return require('./photos/safetyFactors.png');
    case IconsName.sun:
      return require('./photos/sun.png');
    case IconsName.t_category:
      return require('./photos/t_category.png');
    case IconsName.tdriver:
      return require('./photos/tdriver.png');
    case IconsName.translate:
      return require('./photos/translate.png');
    case IconsName.united_kingdom:
      return require('./photos/UK.png');
    case IconsName.W1:
      return require('./photos/W1.png');
    case IconsName.W2:
      return require('./photos/W2.png');
    case IconsName.W3:
      return require('./photos/W3.png');
    case IconsName.W4:
      return require('./photos/W4.png');
    case IconsName.W5:
      return require('./photos/W5.png');
    case IconsName.W6:
      return require('./photos/W6.png');
    case IconsName.W7:
      return require('./photos/W7.png');
    case IconsName.W8:
      return require('./photos/W8.png');
    case IconsName.W9:
      return require('./photos/W9.png');
    case IconsName.W9_old:
      return require('./photos/W9_old.png');
    case IconsName.W10:
      return require('./photos/sun.png');
    case IconsName.W11:
      return require('./photos/W11.png');
    case IconsName.W12:
      return require('./photos/W12.png');
    case IconsName.W13:
      return require('./photos/W13.png');
    case IconsName.W14:
      return require('./photos/W14.png');
    case IconsName.W15:
      return require('./photos/W15.png');
    case IconsName.W16:
      return require('./photos/W16.png');
    case IconsName.W17:
      return require('./photos/W17.png');
    case IconsName.W18:
      return require('./photos/W18.png');
    case IconsName.W19:
      return require('./photos/W19.png');
    case IconsName.W20:
      return require('./photos/W20.png');
    case IconsName.logOut:
      return require('./photos/log_out.png');
    case IconsName.lessons:
      return require('./photos/lessons.png');
    case IconsName.driver_license:
      return require('./photos/driver_license.png');
    case IconsName.driving_pass:
      return require('./photos/driving_pass.png');
    case IconsName.steering_wheel:
      return require('./photos/steering_wheel.png');
    case IconsName.sport_car:
      return require('./photos/sport_car.png');
    case IconsName.b1_category:
      return require('./photos/b1_category.png');
    case IconsName.running:
      return require('./photos/running.png');
    case IconsName.note:
      return require('./photos/note.png');
    case IconsName.alarm_clock:
      return require('./photos/alarm-clock.png');
    case IconsName.report:
      return require('./photos/report.png');
    case IconsName.police_cap:
      return require('./photos/police-cap.png');
    case IconsName.police_cap_fail:
      return require('./photos/police-cap-fail.png');
  }
}
